name: Flow Type Checker

on: [push, pull_request]

jobs:
  flow:
    name: Check Types with Flow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: List directory content
      run: ls -al

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Flow
      run: npm install --save-dev flow-bin

    - name: Run Flow
      run: npx flow
