name: Format

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    format:
        runs-on: ubuntu-latest
        name: Format
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: Prettier
              id: prettier-run
              run: npx prettier --check .
